name: say_no_waste
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.17.0
  flutter_slidable: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Regular.ttf
          weight: 700
  assets:
    - images/splash.png
    - images/google.png
    - images/bin.png
    - images/sign-up-bg.png
    - images/box.png
    - images/storage_icon.png
    - images/cart_bef.png
    - images/share_bef.png
    - images/user_bef.png
    - images/dairy-icon.png
    - images/fruit-icon.png
    - images/meat-icon.png
    - images/snack-icon.png
    - images/vegetable-icon.png


  
